//go:generate go run embd.go

package main

import (
	"fmt"
	"time"

	"github.com/dexyk/stringosim"
)

var LocationNames = allLocations()

type TZData struct {
	Name     string
	Location *time.Location
}

func GetTZData(name string) (TZData, error) {
	tzd := TZData{}

	var curDistance int
	var curMatchTz string

	for tzname, locations := range tzmap {
		for _, s := range locations {
			dist := stringosim.Levenshtein([]rune(name), []rune(s),
				stringosim.LevenshteinSimilarityOptions{
					InsertCost:      1,
					DeleteCost:      3,
					SubstituteCost:  5,
					CaseInsensitive: true,
				})

			if tzd.Name == "" || dist < curDistance {
				tzd.Name = s
				curDistance = dist
				curMatchTz = tzname
			}
		}
	}

	if curDistance > 8 {
		return tzd, fmt.Errorf("location not found")
	}

	loc, err := load(curMatchTz)
	if err != nil {
		return tzd, err
	}
	tzd.Location = loc

	return tzd, nil
}

func load(name string) (*time.Location, error) {
	if data, ok := tzdata[name]; ok {
		return time.LoadLocationFromTZData(name, data)
	}
	return nil, fmt.Errorf("unknown timezone: %s", name)
}

func allLocations() (a []string) {
	for _, locations := range tzmap {
		for _, loc := range locations {
			a = append(a, loc)
		}
	}
	return a
}

var tzmap = map[string][]string{
	"Africa/Abidjan": []string{
		"Abidjan",
		"Abobo",
		"Bouaké",
	},
	"Africa/Accra": []string{
		"Accra",
		"Kumasi",
	},
	"Africa/Addis_Ababa": []string{
		"Addis Ababa",
	},
	"Africa/Algiers": []string{
		"Algiers",
		"Boumerdas",
		"Oran",
		"Tébessa",
		"Constantine",
	},
	"Africa/Asmara": []string{
		"Asmara",
	},
	"Africa/Bamako": []string{
		"Bamako",
	},
	"Africa/Bangui": []string{
		"Bangui",
	},
	"Africa/Blantyre": []string{
		"Lilongwe",
		"Blantyre",
	},
	"Africa/Brazzaville": []string{
		"Brazzaville",
		"Pointe-Noire",
	},
	"Africa/Cairo": []string{
		"Cairo",
		"Alexandria",
		"Giza",
		"Port Said",
		"Suez",
		"Al Maḩallah al Kubrá",
		"Luxor",
		"Asyūţ",
		"Al Manşūrah",
	},
	"Africa/Casablanca": []string{
		"Casablanca",
		"Rabat",
		"Fès",
		"Sale",
		"Marrakesh",
		"Agadir",
		"Tangier",
		"Meknès",
	},
	"Africa/Conakry": []string{
		"Camayenne",
		"Conakry",
	},
	"Africa/Dakar": []string{
		"Dakar",
		"Pikine",
		"Touba",
	},
	"Africa/Dar_es_Salaam": []string{
		"Dar es Salaam",
		"Mwanza",
	},
	"Africa/Djibouti": []string{
		"Djibouti",
	},
	"Africa/Douala": []string{
		"Douala",
		"Yaoundé",
		"Garoua",
		"Kousséri",
	},
	"Africa/Freetown": []string{
		"Freetown",
	},
	"Africa/Harare": []string{
		"Harare",
		"Bulawayo",
	},
	"Africa/Johannesburg": []string{
		"Cape Town",
		"Durban",
		"Johannesburg",
		"Soweto",
		"Pretoria",
		"Port Elizabeth",
		"Pietermaritzburg",
		"Benoni",
		"Tembisa",
		"East London",
		"Vereeniging",
		"Bloemfontein",
		"Boksburg",
		"Welkom",
	},
	"Africa/Juba": []string{
		"Juba",
	},
	"Africa/Kampala": []string{
		"Kampala",
	},
	"Africa/Khartoum": []string{
		"Khartoum",
		"Omdurman",
		"Nyala",
		"Port Sudan",
	},
	"Africa/Kigali": []string{
		"Kigali",
	},
	"Africa/Kinshasa": []string{
		"Kinshasa",
		"Masina",
	},
	"Africa/Lagos": []string{
		"Lagos",
		"Kano",
		"Ibadan",
		"Kaduna",
		"Port Harcourt",
		"Benin City",
		"Maiduguri",
		"Zaria",
		"Aba",
		"Jos",
		"Ilorin",
		"Oyo",
		"Enugu",
		"Abeokuta",
		"Abuja",
		"Sokoto",
		"Onitsha",
		"Warri",
		"Ebute Ikorodu",
		"Okene",
		"Calabar",
		"Uyo",
		"Katsina",
		"Ado-Ekiti",
		"Akure",
	},
	"Africa/Libreville": []string{
		"Libreville",
	},
	"Africa/Lome": []string{
		"Lomé",
	},
	"Africa/Luanda": []string{
		"Luanda",
	},
	"Africa/Lubumbashi": []string{
		"Lubumbashi",
		"Mbuji-Mayi",
		"Kisangani",
		"Kananga",
		"Likasi",
		"Kolwezi",
	},
	"Africa/Lusaka": []string{
		"Lusaka",
	},
	"Africa/Maputo": []string{
		"Maputo",
		"Matola",
		"Beira",
	},
	"Africa/Mogadishu": []string{
		"Mogadishu",
		"Hargeysa",
	},
	"Africa/Monrovia": []string{
		"Monrovia",
	},
	"Africa/Nairobi": []string{
		"Nairobi",
		"Mombasa",
	},
	"Africa/Ndjamena": []string{
		"N'Djamena",
	},
	"Africa/Niamey": []string{
		"Niamey",
	},
	"Africa/Nouakchott": []string{
		"Nouakchott",
	},
	"Africa/Ouagadougou": []string{
		"Ouagadougou",
	},
	"Africa/Porto-Novo": []string{
		"Cotonou",
	},
	"Africa/Tripoli": []string{
		"Tripoli",
		"Benghazi",
	},
	"Africa/Tunis": []string{
		"Tunis",
	},
	"America/Argentina/Buenos_Aires": []string{
		"Buenos Aires",
		"La Plata",
		"Mar del Plata",
		"Quilmes",
	},
	"America/Argentina/Cordoba": []string{
		"Córdoba",
		"Rosario",
		"Santa Fe de la Vera Cruz",
	},
	"America/Argentina/Mendoza": []string{
		"Mendoza",
	},
	"America/Argentina/Salta": []string{
		"Salta",
	},
	"America/Argentina/San_Juan": []string{
		"San Juan",
	},
	"America/Argentina/Tucuman": []string{
		"San Miguel de Tucumán",
	},
	"America/Asuncion": []string{
		"Asunción",
	},
	"America/Bahia": []string{
		"Salvador",
		"Feira de Santana",
	},
	"America/Belem": []string{
		"Belém",
		"Ananindeua",
	},
	"America/Bogota": []string{
		"Bogotá",
		"Cali",
		"Medellín",
		"House' s Joe Arroyo",
		"Barranquilla",
		"Cartagena",
		"Cúcuta",
		"Bucaramanga",
		"Pereira",
		"Santa Marta",
		"Ibagué",
	},
	"America/Campo_Grande": []string{
		"Campo Grande",
	},
	"America/Cancun": []string{
		"Cancún",
	},
	"America/Caracas": []string{
		"Caracas",
		"Maracaibo",
		"Maracay",
		"Valencia",
		"Barquisimeto",
		"Ciudad Guayana",
		"Barcelona",
	},
	"America/Chicago": []string{
		"Chicago",
		"Houston",
		"San Antonio",
		"Dallas",
		"Austin",
		"Fort Worth",
		"Memphis",
		"New South Memphis",
		"Oklahoma City",
		"Milwaukee",
		"Nashville",
		"Kansas City",
		"Omaha",
	},
	"America/Chihuahua": []string{
		"Chihuahua",
	},
	"America/Cuiaba": []string{
		"Cuiabá",
	},
	"America/Denver": []string{
		"Denver",
		"El Paso",
		"Albuquerque",
		"Colorado Springs",
	},
	"America/Detroit": []string{
		"Detroit",
	},
	"America/Edmonton": []string{
		"Calgary",
		"Edmonton",
	},
	"America/El_Salvador": []string{
		"San Salvador",
	},
	"America/Fortaleza": []string{
		"Fortaleza",
		"São Luís",
		"Natal",
		"Teresina",
		"João Pessoa",
	},
	"America/Guatemala": []string{
		"Guatemala City",
		"Mixco",
	},
	"America/Guayaquil": []string{
		"Guayaquil",
		"Quito",
	},
	"America/Havana": []string{
		"Havana",
		"Santiago de Cuba",
	},
	"America/Hermosillo": []string{
		"Hermosillo",
	},
	"America/Indiana/Indianapolis": []string{
		"Indianapolis",
	},
	"America/Jamaica": []string{
		"Kingston",
		"New Kingston",
	},
	"America/La_Paz": []string{
		"Santa Cruz de la Sierra",
		"Cochabamba",
		"La Paz",
	},
	"America/Lima": []string{
		"Lima",
		"Arequipa",
		"Callao",
		"Trujillo",
		"Chiclayo",
		"Iquitos",
	},
	"America/Los_Angeles": []string{
		"Los Angeles",
		"San Diego",
		"San Jose",
		"San Francisco",
		"Seattle",
		"Portland",
		"Las Vegas",
		"Fresno",
		"Sacramento",
		"Long Beach",
		"Oakland",
	},
	"America/Maceio": []string{
		"Maceió",
		"Aracaju",
	},
	"America/Managua": []string{
		"Managua",
	},
	"America/Manaus": []string{
		"Manaus",
	},
	"America/Matamoros": []string{
		"Reynosa",
		"Heroica Matamoros",
	},
	"America/Mazatlan": []string{
		"Culiacán",
	},
	"America/Merida": []string{
		"Mérida",
	},
	"America/Mexico_City": []string{
		"Mexico City",
		"Iztapalapa",
		"Ecatepec",
		"Guadalajara",
		"Puebla",
		"Ciudad Nezahualcoyotl",
		"Gustavo Adolfo Madero",
		"León de los Aldama",
		"Zapopan",
		"Naucalpan de Juárez",
		"Álvaro Obregón",
		"Tlalnepantla",
		"San Luis Potosí",
		"Aguascalientes",
		"Acapulco de Juárez",
		"Coyoacán",
		"Santiago de Querétaro",
		"Tlalpan",
		"Morelia",
		"Veracruz",
		"Santa María Chimalhuacán",
		"Cuauhtémoc",
		"Adolfo López Mateos",
		"Toluca",
		"Tlaquepaque",
		"Tuxtla",
		"Cuautitlán Izcalli",
		"Venustiano Carranza",
		"Azcapotzalco",
		"Xalapa de Enríquez",
	},
	"America/Monterrey": []string{
		"Monterrey",
		"Guadalupe",
		"Saltillo",
		"Torreon",
		"Victoria de Durango",
		"San Nicolás de los Garza",
	},
	"America/Montevideo": []string{
		"Montevideo",
	},
	"America/New_York": []string{
		"New York City",
		"Brooklyn",
		"Queens",
		"Philadelphia",
		"Manhattan",
		"The Bronx",
		"Jacksonville",
		"Columbus",
		"Charlotte",
		"Boston",
		"Baltimore",
		"Washington, D.C.",
		"South Boston",
		"Staten Island",
		"Atlanta",
		"Virginia Beach",
		"Raleigh",
		"Miami",
	},
	"America/Ojinaga": []string{
		"Ciudad Juárez",
	},
	"America/Phoenix": []string{
		"Phoenix",
		"Tucson",
		"Mesa",
	},
	"America/Port-au-Prince": []string{
		"Port-au-Prince",
		"Carrefour",
	},
	"America/Puerto_Rico": []string{
		"San Juan",
	},
	"America/Recife": []string{
		"Recife",
		"Jaboatão",
		"Jaboatão dos Guararapes",
	},
	"America/Santiago": []string{
		"Santiago",
		"Puente Alto",
	},
	"America/Santo_Domingo": []string{
		"Santo Domingo",
		"Santiago de los Caballeros",
		"Santo Domingo Oeste",
		"Santo Domingo Este",
	},
	"America/Sao_Paulo": []string{
		"São Paulo",
		"Rio de Janeiro",
		"Belo Horizonte",
		"Brasília",
		"Curitiba",
		"Porto Alegre",
		"Goiânia",
		"Guarulhos",
		"Campinas",
		"Nova Iguaçu",
		"Duque de Caxias",
		"São Bernardo do Campo",
		"Osasco",
		"Santo André",
		"Contagem",
		"Ribeirão Preto",
		"São José dos Campos",
		"Uberlândia",
		"Sorocaba",
		"Aparecida de Goiânia",
		"Londrina",
		"Juiz de Fora",
		"Belford Roxo",
		"Joinville",
		"Niterói",
		"São João de Meriti",
		"Florianópolis",
		"Santos",
	},
	"America/Tegucigalpa": []string{
		"Tegucigalpa",
		"San Pedro Sula",
	},
	"America/Tijuana": []string{
		"Tijuana",
		"Mexicali",
	},
	"America/Toronto": []string{
		"Toronto",
		"Montréal",
		"Ottawa",
		"Mississauga",
		"North York",
		"Scarborough",
		"Québec",
		"Hamilton",
		"Brampton",
	},
	"America/Vancouver": []string{
		"Vancouver",
	},
	"America/Winnipeg": []string{
		"Winnipeg",
	},
	"Asia/Aden": []string{
		"Sanaa",
		"Al Ḩudaydah",
		"Ta‘izz",
		"Aden",
	},
	"Asia/Almaty": []string{
		"Almaty",
		"Karagandy",
		"Shymkent",
	},
	"Asia/Amman": []string{
		"Amman",
		"Zarqa",
	},
	"Asia/Ashgabat": []string{
		"Ashgabat",
	},
	"Asia/Baghdad": []string{
		"Baghdad",
		"Basrah",
		"Al Mawşil al Jadīdah",
		"Al Başrah al Qadīmah",
		"Mosul",
		"Erbil",
		"Abū Ghurayb",
		"As Sulaymānīyah",
		"Kirkuk",
		"Najaf",
		"Karbala",
	},
	"Asia/Baku": []string{
		"Baku",
	},
	"Asia/Bangkok": []string{
		"Bangkok",
	},
	"Asia/Barnaul": []string{
		"Barnaul",
	},
	"Asia/Beirut": []string{
		"Beirut",
		"Ra’s Bayrūt",
	},
	"Asia/Bishkek": []string{
		"Bishkek",
	},
	"Asia/Colombo": []string{
		"Colombo",
	},
	"Asia/Damascus": []string{
		"Aleppo",
		"Damascus",
		"Homs",
		"Ḩamāh",
	},
	"Asia/Dhaka": []string{
		"Dhaka",
		"Chittagong",
		"Khulna",
		"Rājshāhi",
	},
	"Asia/Dubai": []string{
		"Dubai",
		"Abu Dhabi",
		"Sharjah",
	},
	"Asia/Dushanbe": []string{
		"Dushanbe",
	},
	"Asia/Hebron": []string{
		"East Jerusalem",
	},
	"Asia/Ho_Chi_Minh": []string{
		"Ho Chi Minh City",
		"Hanoi",
		"Da Nang",
		"Haiphong",
	},
	"Asia/Hong_Kong": []string{
		"Hong Kong",
		"Kowloon",
	},
	"Asia/Irkutsk": []string{
		"Irkutsk",
	},
	"Asia/Jakarta": []string{
		"Jakarta",
		"Surabaya",
		"Medan",
		"Bandung",
		"Bekasi",
		"Palembang",
		"Tangerang",
		"South Tangerang",
		"Semarang",
		"Depok",
		"Padang",
		"Bandar Lampung",
		"Bogor",
		"Malang",
		"Pekanbaru",
		"Yogyakarta",
		"Situbondo",
		"Surakarta",
		"Cimahi",
		"Jambi City",
	},
	"Asia/Jerusalem": []string{
		"Jerusalem",
		"Tel Aviv",
	},
	"Asia/Kabul": []string{
		"Kabul",
	},
	"Asia/Karachi": []string{
		"Karachi",
		"Lahore",
		"Faisalābad",
		"Rawalpindi",
		"Multān",
		"Hyderabad",
		"Gujrānwāla",
		"Peshawar",
		"Rahim Yar Khan",
		"Quetta",
		"Muzaffarābād",
		"Battagram",
		"Kotli",
		"Islamabad",
		"Bahawalpur",
		"Sargodha",
		"Sialkot",
		"Sukkur",
	},
	"Asia/Kathmandu": []string{
		"Kathmandu",
	},
	"Asia/Kolkata": []string{
		"Mumbai",
		"Delhi",
		"Bengaluru",
		"Kolkata",
		"Chennai",
		"Ahmedabad",
		"Hyderabad",
		"Pune",
		"Sūrat",
		"Kanpur",
		"Jaipur",
		"Navi Mumbai",
		"Lucknow",
		"Nagpur",
		"Indore",
		"Patna",
		"Bhopal",
		"Ludhiāna",
		"Tirunelveli",
		"Agra",
		"Vadodara",
		"Gorakhpur",
		"Nashik",
		"Pimpri",
		"Kalyān",
		"Thāne",
		"Meerut",
		"Nowrangapur",
		"Faridabad",
		"Ghāziābād",
		"Dombivli",
		"Rājkot",
		"Varanasi",
		"Amritsar",
		"Allahābād",
		"Visakhapatnam",
		"Teni",
		"Jabalpur",
		"Hāora",
		"Aurangabad",
		"Shivaji Nagar",
		"Solāpur",
		"Srinagar",
		"Chandigarh",
		"Coimbatore",
		"Jodhpur",
		"Madurai",
		"Guwahati",
		"Gwalior",
		"Vijayawada",
		"Mysore",
		"Ranchi",
		"Hubli",
		"Jalandhar",
		"Thiruvananthapuram",
		"Salem",
		"Tiruchirappalli",
		"Kota",
		"Bhubaneshwar",
		"Alīgarh",
		"Bareilly",
		"Morādābād",
		"Bhiwandi",
		"Raipur",
		"Gorakhpur",
		"Bhilai",
		"Jamshedpur",
		"Borivli",
		"Cochin",
		"Amrāvati",
		"Sāngli",
		"Cuttack",
		"Bīkaner",
		"Warangal",
		"Bhavnagar",
		"Nanded",
		"Raurkela",
		"Guntur",
		"Dehra Dūn",
		"Bhayandar",
		"Durgapur",
		"Ajmer",
		"Ulhasnagar",
		"Kolhāpur",
		"Shiliguri",
		"Bilimora",
		"Karol Bāgh",
		"Āsansol",
		"Jamnagar",
		"Sahāranpur",
		"Gulbarga",
		"Bhātpāra",
		"Jammu",
		"Kurnool",
		"Ujjain",
		"Rāmgundam",
		"Shyamnagar",
		"Nangi",
		"Kozhikode",
		"Mālegaon",
		"Davangere",
		"Jalgaon",
		"Akola",
		"Belgaum",
		"Gaya",
		"Udaipur",
		"Korba",
		"Bokāro",
		"Mangalore",
		"Jhānsi",
	},
	"Asia/Krasnoyarsk": []string{
		"Krasnoyarsk",
	},
	"Asia/Kuala_Lumpur": []string{
		"Kota Bharu",
		"Kuala Lumpur",
		"Klang",
		"Kampung Baru Subang",
		"Johor Bahru",
		"Subang Jaya",
		"Ipoh",
		"Petaling Jaya",
		"Shah Alam",
	},
	"Asia/Kuching": []string{
		"Kuching",
		"Kota Kinabalu",
	},
	"Asia/Kuwait": []string{
		"Al Aḩmadī",
	},
	"Asia/Macau": []string{
		"Macau",
	},
	"Asia/Makassar": []string{
		"Makassar",
		"Denpasar",
		"City of Balikpapan",
		"Banjarmasin",
		"Manado",
		"Balikpapan",
	},
	"Asia/Manila": []string{
		"Quezon City",
		"Manila",
		"Caloocan City",
		"Budta",
		"Davao",
		"Malingao",
		"Cebu City",
		"General Santos",
		"Taguig",
		"Pasig City",
		"Las Piñas",
		"Antipolo",
		"Makati City",
		"Zamboanga",
		"Bacolod City",
		"Mansilingan",
		"Cagayan de Oro",
		"Dasmariñas",
		"Pasay",
	},
	"Asia/Muscat": []string{
		"Muscat",
	},
	"Asia/Novokuznetsk": []string{
		"Novokuznetsk",
		"Kemerovo",
	},
	"Asia/Novosibirsk": []string{
		"Novosibirsk",
	},
	"Asia/Omsk": []string{
		"Omsk",
	},
	"Asia/Phnom_Penh": []string{
		"Phnom Penh",
		"Takeo",
	},
	"Asia/Pontianak": []string{
		"Pontianak",
	},
	"Asia/Pyongyang": []string{
		"Pyongyang",
		"Hamhŭng",
		"Namp’o",
		"Sunch’ŏn",
	},
	"Asia/Riyadh": []string{
		"Riyadh",
		"Jeddah",
		"Mecca",
		"Medina",
		"Sulţānah",
		"Dammam",
		"Ta’if",
		"Tabuk",
		"Al Kharj",
	},
	"Asia/Seoul": []string{
		"Seoul",
		"Busan",
		"Incheon",
		"Daegu",
		"Daejeon",
		"Gwangju",
		"Suwon",
		"Goyang-si",
		"Seongnam-si",
		"Ulsan",
		"Bucheon-si",
		"Jeonju",
		"Ansan-si",
		"Cheongju-si",
		"Anyang-si",
		"Changwon",
		"Pohang",
		"Uijeongbu-si",
		"Hwaseong-si",
		"Masan",
	},
	"Asia/Shanghai": []string{
		"Shanghai",
		"Beijing",
		"Tianjin",
		"Guangzhou",
		"Shenzhen",
		"Wuhan",
		"Dongguan",
		"Chongqing",
		"Chengdu",
		"Nanjing",
		"Nanchong",
		"Xi’an",
		"Shenyang",
		"Hangzhou",
		"Harbin",
		"Tai’an",
		"Suzhou",
		"Shantou",
		"Jinan",
		"Zhengzhou",
		"Changchun",
		"Dalian",
		"Kunming",
		"Qingdao",
		"Foshan",
		"Puyang",
		"Wuxi",
		"Xiamen",
		"Tianshui",
		"Ningbo",
		"Shiyan",
		"Taiyuan",
		"Tangshan",
		"Hefei",
		"Zibo",
		"Changsha",
		"Shijiazhuang",
		"Huai’an",
		"Lanzhou",
		"Yunfu",
		"Nanchang",
		"Dadonghai",
		"Ordos",
		"Jilin",
		"Kunshan",
		"Xinyang",
		"Fushun",
		"Luoyang",
		"Guankou",
		"Handan",
		"Baotou",
		"Xuchang",
		"Yueyang",
		"Anshan",
		"Tongshan",
		"Fuzhou",
		"Guiyang",
		"Lijiang",
		"Datong",
		"Changshu City",
		"Xianyang",
		"Huainan",
		"Jieyang",
		"Zhu Cheng City",
		"Baoding",
		"Benxi",
		"Changzhou",
		"Huaibei",
		"Kaifeng",
		"Pingdingshan",
		"Qiqihar",
		"Wenzhou",
		"Nanning",
		"Anyang",
		"Hohhot",
		"Shangyu",
		"Xining",
		"Qinhuangdao",
		"Hengyang",
		"Xinxiang",
		"Hegang",
		"Langfang",
		"Zhumadian",
		"Yantai",
		"Zhuzhou",
		"Changzhi",
		"Zhangjiakou",
		"Zigong",
		"Fuxin",
		"Huangshi",
		"Liaoyang",
		"Xiangtan",
		"Puyang Chengguanzhen",
		"Nantong",
		"Mudanjiang",
		"Guilin",
		"Zhenjiang",
		"Dandong",
		"Shaoguan",
		"Yancheng",
		"Panshan",
		"Haikou",
		"Taizhou",
		"Xingtai",
		"Jinzhou",
		"Shuangyashan",
		"Luancheng",
		"Yingkou",
		"Zhangzhou",
		"Bengbu",
		"Siping",
		"Huai'an",
		"Jiamusi",
		"Neijiang",
		"Yangzhou",
		"Guli",
		"Tanggu",
		"Jiangmen",
		"Cangzhou",
		"Changde",
		"Jiaozuo",
		"Tonghua",
		"Wuhu",
		"Zhuhai",
		"Shashi",
		"Wuwei",
		"Qionghai",
		"Yichang",
		"Yinchuan",
		"Jiaojiangcun",
		"Zunyi",
		"Jiaxing",
		"Liaoyuan",
		"Xiangyang",
		"Dadukou",
		"Hengshui",
		"Jining",
		"Wenshan City",
		"Chengde",
		"Bei’an",
		"Luqiao",
		"Chaozhou",
		"Shaoxing",
		"Luohe",
		"Yangquan",
	},
	"Asia/Singapore": []string{
		"Singapore",
	},
	"Asia/Taipei": []string{
		"Taipei",
		"Kaohsiung",
		"Taichung",
		"Tainan",
		"Banqiao",
	},
	"Asia/Tashkent": []string{
		"Tashkent",
		"Namangan",
	},
	"Asia/Tbilisi": []string{
		"Tbilisi",
	},
	"Asia/Tehran": []string{
		"Tehran",
		"Mashhad",
		"Isfahan",
		"Karaj",
		"Tabriz",
		"Shiraz",
		"Qom",
		"Ahvaz",
		"Pasragad Branch",
		"Kahrīz",
		"Kermanshah",
		"Rasht",
		"Kerman",
		"Orūmīyeh",
		"Zahedan",
		"Hamadān",
		"Āzādshahr",
		"Arāk",
		"Yazd",
	},
	"Asia/Tokyo": []string{
		"Tokyo",
		"Yokohama",
		"Osaka",
		"Nagoya",
		"Sapporo",
		"Kobe",
		"Kyoto",
		"Fukuoka",
		"Kawasaki",
		"Saitama",
		"Hiroshima",
		"Yono",
		"Sendai",
		"Kitakyushu",
		"Chiba",
		"Sakai",
		"Shizuoka",
		"Kumamoto",
		"Okayama",
		"Hamamatsu",
		"Hachiōji",
		"Honchō",
		"Kagoshima",
		"Niigata",
		"Himeji",
		"Matsudo",
		"Nishinomiya-hama",
		"Kawaguchi",
		"Kanazawa",
		"Utsunomiya",
		"Ōita",
		"Matsuyama",
		"Amagasaki",
		"Kurashiki",
		"Yokosuka",
	},
	"Asia/Tomsk": []string{
		"Tomsk",
	},
	"Asia/Ulaanbaatar": []string{
		"Ulan Bator",
	},
	"Asia/Urumqi": []string{
		"Zhongshan",
		"Ürümqi",
		"Zhanjiang",
		"Shihezi",
	},
	"Asia/Vladivostok": []string{
		"Vladivostok",
		"Khabarovsk",
		"Khabarovsk Vtoroy",
	},
	"Asia/Yangon": []string{
		"Yangon",
		"Mandalay",
		"Nay Pyi Taw",
		"Mawlamyine",
	},
	"Asia/Yekaterinburg": []string{
		"Yekaterinburg",
		"Chelyabinsk",
		"Ufa",
		"Perm",
		"Orenburg",
		"Tyumen",
		"Magnitogorsk",
	},
	"Asia/Yerevan": []string{
		"Yerevan",
	},
	"Australia/Adelaide": []string{
		"Adelaide",
	},
	"Australia/Brisbane": []string{
		"Brisbane",
		"Gold Coast",
	},
	"Australia/Melbourne": []string{
		"Melbourne",
	},
	"Australia/Perth": []string{
		"Perth",
	},
	"Australia/Sydney": []string{
		"Sydney",
	},
	"Europe/Amsterdam": []string{
		"Amsterdam",
		"Rotterdam",
		"The Hague",
	},
	"Europe/Astrakhan": []string{
		"Astrakhan",
	},
	"Europe/Athens": []string{
		"Athens",
	},
	"Europe/Belgrade": []string{
		"Belgrade",
		"Pristina",
	},
	"Europe/Berlin": []string{
		"Berlin",
		"Hamburg",
		"Munich",
		"Köln",
		"Frankfurt am Main",
		"Essen",
		"Stuttgart",
		"Dortmund",
		"Düsseldorf",
		"Bremen",
		"Hannover",
		"Leipzig",
		"Duisburg",
		"Nürnberg",
		"Dresden",
		"Wandsbek",
	},
	"Europe/Bratislava": []string{
		"Bratislava",
	},
	"Europe/Brussels": []string{
		"Brussels",
		"Antwerpen",
	},
	"Europe/Bucharest": []string{
		"Bucharest",
	},
	"Europe/Budapest": []string{
		"Budapest",
	},
	"Europe/Chisinau": []string{
		"Chisinau",
	},
	"Europe/Copenhagen": []string{
		"Copenhagen",
	},
	"Europe/Dublin": []string{
		"Dublin",
	},
	"Europe/Helsinki": []string{
		"Helsinki",
	},
	"Europe/Istanbul": []string{
		"Istanbul",
		"Ankara",
		"İzmir",
		"Bursa",
		"Adana",
		"Gaziantep",
		"Konya",
		"Çankaya",
		"Antalya",
		"Bağcılar",
		"Diyarbakır",
		"Kayseri",
		"Üsküdar",
		"Bahçelievler",
		"Umraniye",
		"Mersin",
		"Esenler",
		"Eskişehir",
		"Karabağlar",
		"Muratpaşa",
		"Şanlıurfa",
		"Malatya",
		"Sultangazi",
		"Maltepe",
		"Erzurum",
	},
	"Europe/Kaliningrad": []string{
		"Kaliningrad",
	},
	"Europe/Kiev": []string{
		"Kyiv",
		"Kharkiv",
		"Dnipro",
		"Donetsk",
		"Odessa",
		"Lviv",
		"Kryvyi Rih",
		"Mykolayiv",
		"Mariupol",
	},
	"Europe/Kirov": []string{
		"Kirov",
	},
	"Europe/Lisbon": []string{
		"Lisbon",
	},
	"Europe/London": []string{
		"London",
		"Birmingham",
		"Liverpool",
		"Nottingham",
		"Sheffield",
		"Bristol",
		"Glasgow",
		"Leicester",
		"Edinburgh",
		"Leeds",
		"Cardiff",
	},
	"Europe/Madrid": []string{
		"Madrid",
		"Barcelona",
		"Valencia",
		"Sevilla",
		"Zaragoza",
		"Málaga",
		"Murcia",
	},
	"Europe/Minsk": []string{
		"Minsk",
		"Gomel",
	},
	"Europe/Moscow": []string{
		"Moscow",
		"Saint Petersburg",
		"Nizhniy Novgorod",
		"Kazan",
		"Rostov-na-Donu",
		"Voronezh",
		"Krasnodar",
		"Yaroslavl",
		"Ryazan’",
		"Lipetsk",
		"Penza",
		"Naberezhnyye Chelny",
		"Kalininskiy",
		"Makhachkala",
		"Tula",
		"Cheboksary",
		"Bryansk",
		"Ivanovo",
	},
	"Europe/Oslo": []string{
		"Oslo",
	},
	"Europe/Paris": []string{
		"Paris",
		"Marseille",
		"Lyon",
		"Toulouse",
	},
	"Europe/Prague": []string{
		"Prague",
	},
	"Europe/Riga": []string{
		"Riga",
	},
	"Europe/Rome": []string{
		"Rome",
		"Milan",
		"Naples",
		"Turin",
		"Palermo",
		"Genoa",
	},
	"Europe/Samara": []string{
		"Samara",
		"Tol’yatti",
		"Izhevsk",
	},
	"Europe/Sarajevo": []string{
		"Sarajevo",
	},
	"Europe/Saratov": []string{
		"Saratov",
	},
	"Europe/Simferopol": []string{
		"Sevastopol",
	},
	"Europe/Skopje": []string{
		"Skopje",
	},
	"Europe/Sofia": []string{
		"Sofia",
	},
	"Europe/Stockholm": []string{
		"Stockholm",
		"Göteborg",
	},
	"Europe/Ulyanovsk": []string{
		"Ulyanovsk",
	},
	"Europe/Vienna": []string{
		"Vienna",
	},
	"Europe/Vilnius": []string{
		"Vilnius",
	},
	"Europe/Volgograd": []string{
		"Volgograd",
	},
	"Europe/Warsaw": []string{
		"Warsaw",
		"Łódź",
		"Kraków",
		"Wrocław",
		"Poznań",
		"Gdańsk",
	},
	"Europe/Zagreb": []string{
		"Zagreb",
	},
	"Europe/Zaporozhye": []string{
		"Zaporizhia",
		"Luhansk",
	},
	"Indian/Antananarivo": []string{
		"Antananarivo",
	},
	"Pacific/Auckland": []string{
		"Auckland",
	},
}
