package main

var LocationNames = allLocations()

func allLocations() (a []string) {
	for loc, _ := range tzmap {
		a = append(a, loc)
	}
	sort.Strings(a)
	return a
}

var tzmap = map[string]string{
	"Aba":                        "Africa/Lagos",
	"Abeokuta":                   "Africa/Lagos",
	"Abidjan":                    "Africa/Abidjan",
	"Abobo":                      "Africa/Abidjan",
	"Abu Dhabi":                  "Asia/Dubai",
	"Abuja":                      "Africa/Lagos",
	"Abū Ghurayb":                "Asia/Baghdad",
	"Acapulco de Juárez":         "America/Mexico_City",
	"Accra":                      "Africa/Accra",
	"Adana":                      "Europe/Istanbul",
	"Addis Ababa":                "Africa/Addis_Ababa",
	"Adelaide":                   "Australia/Adelaide",
	"Aden":                       "Asia/Aden",
	"Ado-Ekiti":                  "Africa/Lagos",
	"Adolfo López Mateos":        "America/Mexico_City",
	"Agadir":                     "Africa/Casablanca",
	"Agra":                       "Asia/Kolkata",
	"Aguascalientes":             "America/Mexico_City",
	"Ahmedabad":                  "Asia/Kolkata",
	"Ahvaz":                      "Asia/Tehran",
	"Ajmer":                      "Asia/Kolkata",
	"Akola":                      "Asia/Kolkata",
	"Akure":                      "Africa/Lagos",
	"Al Aḩmadī":                  "Asia/Kuwait",
	"Al Başrah al Qadīmah":       "Asia/Baghdad",
	"Al Kharj":                   "Asia/Riyadh",
	"Al Manşūrah":                "Africa/Cairo",
	"Al Mawşil al Jadīdah":       "Asia/Baghdad",
	"Al Maḩallah al Kubrá":       "Africa/Cairo",
	"Al Ḩudaydah":                "Asia/Aden",
	"Albuquerque":                "America/Denver",
	"Aleppo":                     "Asia/Damascus",
	"Alexandria":                 "Africa/Cairo",
	"Algiers":                    "Africa/Algiers",
	"Allahābād":                  "Asia/Kolkata",
	"Almaty":                     "Asia/Almaty",
	"Alīgarh":                    "Asia/Kolkata",
	"Amagasaki":                  "Asia/Tokyo",
	"Amman":                      "Asia/Amman",
	"Amritsar":                   "Asia/Kolkata",
	"Amrāvati":                   "Asia/Kolkata",
	"Amsterdam":                  "Europe/Amsterdam",
	"Ananindeua":                 "America/Belem",
	"Ankara":                     "Europe/Istanbul",
	"Ansan-si":                   "Asia/Seoul",
	"Anshan":                     "Asia/Shanghai",
	"Antalya":                    "Europe/Istanbul",
	"Antananarivo":               "Indian/Antananarivo",
	"Antipolo":                   "Asia/Manila",
	"Antwerpen":                  "Europe/Brussels",
	"Anyang":                     "Asia/Shanghai",
	"Anyang-si":                  "Asia/Seoul",
	"Aparecida de Goiânia":       "America/Sao_Paulo",
	"Aracaju":                    "America/Maceio",
	"Arequipa":                   "America/Lima",
	"Arāk":                       "Asia/Tehran",
	"As Sulaymānīyah":            "Asia/Baghdad",
	"Ashgabat":                   "Asia/Ashgabat",
	"Asmara":                     "Africa/Asmara",
	"Astrakhan":                  "Europe/Astrakhan",
	"Asunción":                   "America/Asuncion",
	"Asyūţ":                      "Africa/Cairo",
	"Athens":                     "Europe/Athens",
	"Atlanta":                    "America/New_York",
	"Auckland":                   "Pacific/Auckland",
	"Aurangabad":                 "Asia/Kolkata",
	"Austin":                     "America/Chicago",
	"Azcapotzalco":               "America/Mexico_City",
	"Bacolod City":               "Asia/Manila",
	"Baghdad":                    "Asia/Baghdad",
	"Bahawalpur":                 "Asia/Karachi",
	"Bahçelievler":               "Europe/Istanbul",
	"Baku":                       "Asia/Baku",
	"Balikpapan":                 "Asia/Makassar",
	"Baltimore":                  "America/New_York",
	"Bamako":                     "Africa/Bamako",
	"Bandar Lampung":             "Asia/Jakarta",
	"Bandung":                    "Asia/Jakarta",
	"Bangkok":                    "Asia/Bangkok",
	"Bangui":                     "Africa/Bangui",
	"Banjarmasin":                "Asia/Makassar",
	"Banqiao":                    "Asia/Taipei",
	"Baoding":                    "Asia/Shanghai",
	"Baotou":                     "Asia/Shanghai",
	"Barcelona":                  "Europe/Madrid",
	"Bareilly":                   "Asia/Kolkata",
	"Barnaul":                    "Asia/Barnaul",
	"Barquisimeto":               "America/Caracas",
	"Barranquilla":               "America/Bogota",
	"Basrah":                     "Asia/Baghdad",
	"Battagram":                  "Asia/Karachi",
	"Bağcılar":                   "Europe/Istanbul",
	"Beijing":                    "Asia/Shanghai",
	"Beira":                      "Africa/Maputo",
	"Beirut":                     "Asia/Beirut",
	"Bei’an":                     "Asia/Shanghai",
	"Bekasi":                     "Asia/Jakarta",
	"Belford Roxo":               "America/Sao_Paulo",
	"Belgaum":                    "Asia/Kolkata",
	"Belgrade":                   "Europe/Belgrade",
	"Belo Horizonte":             "America/Sao_Paulo",
	"Belém":                      "America/Belem",
	"Bengaluru":                  "Asia/Kolkata",
	"Bengbu":                     "Asia/Shanghai",
	"Benghazi":                   "Africa/Tripoli",
	"Benin City":                 "Africa/Lagos",
	"Benoni":                     "Africa/Johannesburg",
	"Benxi":                      "Asia/Shanghai",
	"Berlin":                     "Europe/Berlin",
	"Bhavnagar":                  "Asia/Kolkata",
	"Bhayandar":                  "Asia/Kolkata",
	"Bhilai":                     "Asia/Kolkata",
	"Bhiwandi":                   "Asia/Kolkata",
	"Bhopal":                     "Asia/Kolkata",
	"Bhubaneshwar":               "Asia/Kolkata",
	"Bhātpāra":                   "Asia/Kolkata",
	"Bilimora":                   "Asia/Kolkata",
	"Birmingham":                 "Europe/London",
	"Bishkek":                    "Asia/Bishkek",
	"Blantyre":                   "Africa/Blantyre",
	"Bloemfontein":               "Africa/Johannesburg",
	"Bogor":                      "Asia/Jakarta",
	"Bogotá":                     "America/Bogota",
	"Boksburg":                   "Africa/Johannesburg",
	"Bokāro":                     "Asia/Kolkata",
	"Borivli":                    "Asia/Kolkata",
	"Boston":                     "America/New_York",
	"Bouaké":                     "Africa/Abidjan",
	"Boumerdas":                  "Africa/Algiers",
	"Brampton":                   "America/Toronto",
	"Brasília":                   "America/Sao_Paulo",
	"Bratislava":                 "Europe/Bratislava",
	"Brazzaville":                "Africa/Brazzaville",
	"Bremen":                     "Europe/Berlin",
	"Brisbane":                   "Australia/Brisbane",
	"Bristol":                    "Europe/London",
	"Brooklyn":                   "America/New_York",
	"Brussels":                   "Europe/Brussels",
	"Bryansk":                    "Europe/Moscow",
	"Bucaramanga":                "America/Bogota",
	"Bucharest":                  "Europe/Bucharest",
	"Bucheon-si":                 "Asia/Seoul",
	"Budapest":                   "Europe/Budapest",
	"Budta":                      "Asia/Manila",
	"Buenos Aires":               "America/Argentina/Buenos_Aires",
	"Bulawayo":                   "Africa/Harare",
	"Bursa":                      "Europe/Istanbul",
	"Busan":                      "Asia/Seoul",
	"Bīkaner":                    "Asia/Kolkata",
	"Cagayan de Oro":             "Asia/Manila",
	"Cairo":                      "Africa/Cairo",
	"Calabar":                    "Africa/Lagos",
	"Calgary":                    "America/Edmonton",
	"Cali":                       "America/Bogota",
	"Callao":                     "America/Lima",
	"Caloocan City":              "Asia/Manila",
	"Camayenne":                  "Africa/Conakry",
	"Campinas":                   "America/Sao_Paulo",
	"Campo Grande":               "America/Campo_Grande",
	"Cancún":                     "America/Cancun",
	"Cangzhou":                   "Asia/Shanghai",
	"Cape Town":                  "Africa/Johannesburg",
	"Caracas":                    "America/Caracas",
	"Cardiff":                    "Europe/London",
	"Carrefour":                  "America/Port-au-Prince",
	"Cartagena":                  "America/Bogota",
	"Casablanca":                 "Africa/Casablanca",
	"Cebu City":                  "Asia/Manila",
	"Chandigarh":                 "Asia/Kolkata",
	"Changchun":                  "Asia/Shanghai",
	"Changde":                    "Asia/Shanghai",
	"Changsha":                   "Asia/Shanghai",
	"Changshu City":              "Asia/Shanghai",
	"Changwon":                   "Asia/Seoul",
	"Changzhi":                   "Asia/Shanghai",
	"Changzhou":                  "Asia/Shanghai",
	"Chaozhou":                   "Asia/Shanghai",
	"Charlotte":                  "America/New_York",
	"Cheboksary":                 "Europe/Moscow",
	"Chelyabinsk":                "Asia/Yekaterinburg",
	"Chengde":                    "Asia/Shanghai",
	"Chengdu":                    "Asia/Shanghai",
	"Chennai":                    "Asia/Kolkata",
	"Cheongju-si":                "Asia/Seoul",
	"Chiba":                      "Asia/Tokyo",
	"Chicago":                    "America/Chicago",
	"Chiclayo":                   "America/Lima",
	"Chihuahua":                  "America/Chihuahua",
	"Chisinau":                   "Europe/Chisinau",
	"Chittagong":                 "Asia/Dhaka",
	"Chongqing":                  "Asia/Shanghai",
	"Cimahi":                     "Asia/Jakarta",
	"City of Balikpapan":         "Asia/Makassar",
	"Ciudad Guayana":             "America/Caracas",
	"Ciudad Juárez":              "America/Ojinaga",
	"Ciudad Nezahualcoyotl":      "America/Mexico_City",
	"Cochabamba":                 "America/La_Paz",
	"Cochin":                     "Asia/Kolkata",
	"Coimbatore":                 "Asia/Kolkata",
	"Colombo":                    "Asia/Colombo",
	"Colorado Springs":           "America/Denver",
	"Columbus":                   "America/New_York",
	"Conakry":                    "Africa/Conakry",
	"Constantine":                "Africa/Algiers",
	"Contagem":                   "America/Sao_Paulo",
	"Copenhagen":                 "Europe/Copenhagen",
	"Cotonou":                    "Africa/Porto-Novo",
	"Coyoacán":                   "America/Mexico_City",
	"Cuauhtémoc":                 "America/Mexico_City",
	"Cuautitlán Izcalli":         "America/Mexico_City",
	"Cuiabá":                     "America/Cuiaba",
	"Culiacán":                   "America/Mazatlan",
	"Curitiba":                   "America/Sao_Paulo",
	"Cuttack":                    "Asia/Kolkata",
	"Córdoba":                    "America/Argentina/Cordoba",
	"Cúcuta":                     "America/Bogota",
	"Da Nang":                    "Asia/Ho_Chi_Minh",
	"Dadonghai":                  "Asia/Shanghai",
	"Dadukou":                    "Asia/Shanghai",
	"Daegu":                      "Asia/Seoul",
	"Daejeon":                    "Asia/Seoul",
	"Dakar":                      "Africa/Dakar",
	"Dalian":                     "Asia/Shanghai",
	"Dallas":                     "America/Chicago",
	"Damascus":                   "Asia/Damascus",
	"Dammam":                     "Asia/Riyadh",
	"Dandong":                    "Asia/Shanghai",
	"Dar es Salaam":              "Africa/Dar_es_Salaam",
	"Dasmariñas":                 "Asia/Manila",
	"Datong":                     "Asia/Shanghai",
	"Davangere":                  "Asia/Kolkata",
	"Davao":                      "Asia/Manila",
	"Dehra Dūn":                  "Asia/Kolkata",
	"Delhi":                      "Asia/Kolkata",
	"Denpasar":                   "Asia/Makassar",
	"Denver":                     "America/Denver",
	"Depok":                      "Asia/Jakarta",
	"Detroit":                    "America/Detroit",
	"Dhaka":                      "Asia/Dhaka",
	"Diyarbakır":                 "Europe/Istanbul",
	"Djibouti":                   "Africa/Djibouti",
	"Dnipro":                     "Europe/Kiev",
	"Dombivli":                   "Asia/Kolkata",
	"Donetsk":                    "Europe/Kiev",
	"Dongguan":                   "Asia/Shanghai",
	"Dortmund":                   "Europe/Berlin",
	"Douala":                     "Africa/Douala",
	"Dresden":                    "Europe/Berlin",
	"Dubai":                      "Asia/Dubai",
	"Dublin":                     "Europe/Dublin",
	"Duisburg":                   "Europe/Berlin",
	"Duque de Caxias":            "America/Sao_Paulo",
	"Durban":                     "Africa/Johannesburg",
	"Durgapur":                   "Asia/Kolkata",
	"Dushanbe":                   "Asia/Dushanbe",
	"Düsseldorf":                 "Europe/Berlin",
	"East Jerusalem":             "Asia/Hebron",
	"East London":                "Africa/Johannesburg",
	"Ebute Ikorodu":              "Africa/Lagos",
	"Ecatepec":                   "America/Mexico_City",
	"Edinburgh":                  "Europe/London",
	"Edmonton":                   "America/Edmonton",
	"El Paso":                    "America/Denver",
	"Enugu":                      "Africa/Lagos",
	"Erbil":                      "Asia/Baghdad",
	"Erzurum":                    "Europe/Istanbul",
	"Esenler":                    "Europe/Istanbul",
	"Eskişehir":                  "Europe/Istanbul",
	"Essen":                      "Europe/Berlin",
	"Faisalābad":                 "Asia/Karachi",
	"Faridabad":                  "Asia/Kolkata",
	"Feira de Santana":           "America/Bahia",
	"Florianópolis":              "America/Sao_Paulo",
	"Fort Worth":                 "America/Chicago",
	"Fortaleza":                  "America/Fortaleza",
	"Foshan":                     "Asia/Shanghai",
	"Frankfurt am Main":          "Europe/Berlin",
	"Freetown":                   "Africa/Freetown",
	"Fresno":                     "America/Los_Angeles",
	"Fukuoka":                    "Asia/Tokyo",
	"Fushun":                     "Asia/Shanghai",
	"Fuxin":                      "Asia/Shanghai",
	"Fuzhou":                     "Asia/Shanghai",
	"Fès":                        "Africa/Casablanca",
	"Garoua":                     "Africa/Douala",
	"Gaya":                       "Asia/Kolkata",
	"Gaziantep":                  "Europe/Istanbul",
	"Gdańsk":                     "Europe/Warsaw",
	"General Santos":             "Asia/Manila",
	"Genoa":                      "Europe/Rome",
	"Ghāziābād":                  "Asia/Kolkata",
	"Giza":                       "Africa/Cairo",
	"Glasgow":                    "Europe/London",
	"Goiânia":                    "America/Sao_Paulo",
	"Gold Coast":                 "Australia/Brisbane",
	"Gomel":                      "Europe/Minsk",
	"Gorakhpur":                  "Asia/Kolkata",
	"Goyang-si":                  "Asia/Seoul",
	"Guadalajara":                "America/Mexico_City",
	"Guadalupe":                  "America/Monterrey",
	"Guangzhou":                  "Asia/Shanghai",
	"Guankou":                    "Asia/Shanghai",
	"Guarulhos":                  "America/Sao_Paulo",
	"Guatemala City":             "America/Guatemala",
	"Guayaquil":                  "America/Guayaquil",
	"Guilin":                     "Asia/Shanghai",
	"Guiyang":                    "Asia/Shanghai",
	"Gujrānwāla":                 "Asia/Karachi",
	"Gulbarga":                   "Asia/Kolkata",
	"Guli":                       "Asia/Shanghai",
	"Guntur":                     "Asia/Kolkata",
	"Gustavo Adolfo Madero":      "America/Mexico_City",
	"Guwahati":                   "Asia/Kolkata",
	"Gwalior":                    "Asia/Kolkata",
	"Gwangju":                    "Asia/Seoul",
	"Göteborg":                   "Europe/Stockholm",
	"Hachiōji":                   "Asia/Tokyo",
	"Haikou":                     "Asia/Shanghai",
	"Haiphong":                   "Asia/Ho_Chi_Minh",
	"Hamadān":                    "Asia/Tehran",
	"Hamamatsu":                  "Asia/Tokyo",
	"Hamburg":                    "Europe/Berlin",
	"Hamhŭng":                    "Asia/Pyongyang",
	"Hamilton":                   "America/Toronto",
	"Handan":                     "Asia/Shanghai",
	"Hangzhou":                   "Asia/Shanghai",
	"Hannover":                   "Europe/Berlin",
	"Hanoi":                      "Asia/Ho_Chi_Minh",
	"Harare":                     "Africa/Harare",
	"Harbin":                     "Asia/Shanghai",
	"Hargeysa":                   "Africa/Mogadishu",
	"Havana":                     "America/Havana",
	"Hefei":                      "Asia/Shanghai",
	"Hegang":                     "Asia/Shanghai",
	"Helsinki":                   "Europe/Helsinki",
	"Hengshui":                   "Asia/Shanghai",
	"Hengyang":                   "Asia/Shanghai",
	"Hermosillo":                 "America/Hermosillo",
	"Heroica Matamoros":          "America/Matamoros",
	"Himeji":                     "Asia/Tokyo",
	"Hiroshima":                  "Asia/Tokyo",
	"Ho Chi Minh City":           "Asia/Ho_Chi_Minh",
	"Hohhot":                     "Asia/Shanghai",
	"Homs":                       "Asia/Damascus",
	"Honchō":                     "Asia/Tokyo",
	"Hong Kong":                  "Asia/Hong_Kong",
	"House' s Joe Arroyo":        "America/Bogota",
	"Houston":                    "America/Chicago",
	"Huai'an":                    "Asia/Shanghai",
	"Huaibei":                    "Asia/Shanghai",
	"Huainan":                    "Asia/Shanghai",
	"Huai’an":                    "Asia/Shanghai",
	"Huangshi":                   "Asia/Shanghai",
	"Hubli":                      "Asia/Kolkata",
	"Hwaseong-si":                "Asia/Seoul",
	"Hyderabad":                  "Asia/Kolkata",
	"Hāora":                      "Asia/Kolkata",
	"Ibadan":                     "Africa/Lagos",
	"Ibagué":                     "America/Bogota",
	"Ilorin":                     "Africa/Lagos",
	"Incheon":                    "Asia/Seoul",
	"Indianapolis":               "America/Indiana/Indianapolis",
	"Indore":                     "Asia/Kolkata",
	"Ipoh":                       "Asia/Kuala_Lumpur",
	"Iquitos":                    "America/Lima",
	"Irkutsk":                    "Asia/Irkutsk",
	"Isfahan":                    "Asia/Tehran",
	"Islamabad":                  "Asia/Karachi",
	"Istanbul":                   "Europe/Istanbul",
	"Ivanovo":                    "Europe/Moscow",
	"Izhevsk":                    "Europe/Samara",
	"Iztapalapa":                 "America/Mexico_City",
	"Jabalpur":                   "Asia/Kolkata",
	"Jaboatão":                   "America/Recife",
	"Jaboatão dos Guararapes":    "America/Recife",
	"Jacksonville":               "America/New_York",
	"Jaipur":                     "Asia/Kolkata",
	"Jakarta":                    "Asia/Jakarta",
	"Jalandhar":                  "Asia/Kolkata",
	"Jalgaon":                    "Asia/Kolkata",
	"Jambi City":                 "Asia/Jakarta",
	"Jammu":                      "Asia/Kolkata",
	"Jamnagar":                   "Asia/Kolkata",
	"Jamshedpur":                 "Asia/Kolkata",
	"Jeddah":                     "Asia/Riyadh",
	"Jeonju":                     "Asia/Seoul",
	"Jerusalem":                  "Asia/Jerusalem",
	"Jhānsi":                     "Asia/Kolkata",
	"Jiamusi":                    "Asia/Shanghai",
	"Jiangmen":                   "Asia/Shanghai",
	"Jiaojiangcun":               "Asia/Shanghai",
	"Jiaozuo":                    "Asia/Shanghai",
	"Jiaxing":                    "Asia/Shanghai",
	"Jieyang":                    "Asia/Shanghai",
	"Jilin":                      "Asia/Shanghai",
	"Jinan":                      "Asia/Shanghai",
	"Jining":                     "Asia/Shanghai",
	"Jinzhou":                    "Asia/Shanghai",
	"Jodhpur":                    "Asia/Kolkata",
	"Johannesburg":               "Africa/Johannesburg",
	"Johor Bahru":                "Asia/Kuala_Lumpur",
	"Joinville":                  "America/Sao_Paulo",
	"Jos":                        "Africa/Lagos",
	"João Pessoa":                "America/Fortaleza",
	"Juba":                       "Africa/Juba",
	"Juiz de Fora":               "America/Sao_Paulo",
	"Kabul":                      "Asia/Kabul",
	"Kaduna":                     "Africa/Lagos",
	"Kagoshima":                  "Asia/Tokyo",
	"Kahrīz":                     "Asia/Tehran",
	"Kaifeng":                    "Asia/Shanghai",
	"Kaliningrad":                "Europe/Kaliningrad",
	"Kalininskiy":                "Europe/Moscow",
	"Kalyān":                     "Asia/Kolkata",
	"Kampala":                    "Africa/Kampala",
	"Kampung Baru Subang":        "Asia/Kuala_Lumpur",
	"Kananga":                    "Africa/Lubumbashi",
	"Kanazawa":                   "Asia/Tokyo",
	"Kano":                       "Africa/Lagos",
	"Kanpur":                     "Asia/Kolkata",
	"Kansas City":                "America/Chicago",
	"Kaohsiung":                  "Asia/Taipei",
	"Karabağlar":                 "Europe/Istanbul",
	"Karachi":                    "Asia/Karachi",
	"Karagandy":                  "Asia/Almaty",
	"Karaj":                      "Asia/Tehran",
	"Karbala":                    "Asia/Baghdad",
	"Karol Bāgh":                 "Asia/Kolkata",
	"Kathmandu":                  "Asia/Kathmandu",
	"Katsina":                    "Africa/Lagos",
	"Kawaguchi":                  "Asia/Tokyo",
	"Kawasaki":                   "Asia/Tokyo",
	"Kayseri":                    "Europe/Istanbul",
	"Kazan":                      "Europe/Moscow",
	"Kemerovo":                   "Asia/Novokuznetsk",
	"Kerman":                     "Asia/Tehran",
	"Kermanshah":                 "Asia/Tehran",
	"Khabarovsk":                 "Asia/Vladivostok",
	"Khabarovsk Vtoroy":          "Asia/Vladivostok",
	"Kharkiv":                    "Europe/Kiev",
	"Khartoum":                   "Africa/Khartoum",
	"Khulna":                     "Asia/Dhaka",
	"Kigali":                     "Africa/Kigali",
	"Kingston":                   "America/Jamaica",
	"Kinshasa":                   "Africa/Kinshasa",
	"Kirkuk":                     "Asia/Baghdad",
	"Kirov":                      "Europe/Kirov",
	"Kisangani":                  "Africa/Lubumbashi",
	"Kitakyushu":                 "Asia/Tokyo",
	"Klang":                      "Asia/Kuala_Lumpur",
	"Kobe":                       "Asia/Tokyo",
	"Kolhāpur":                   "Asia/Kolkata",
	"Kolkata":                    "Asia/Kolkata",
	"Kolwezi":                    "Africa/Lubumbashi",
	"Konya":                      "Europe/Istanbul",
	"Korba":                      "Asia/Kolkata",
	"Kota":                       "Asia/Kolkata",
	"Kota Bharu":                 "Asia/Kuala_Lumpur",
	"Kota Kinabalu":              "Asia/Kuching",
	"Kotli":                      "Asia/Karachi",
	"Kousséri":                   "Africa/Douala",
	"Kowloon":                    "Asia/Hong_Kong",
	"Kozhikode":                  "Asia/Kolkata",
	"Kraków":                     "Europe/Warsaw",
	"Krasnodar":                  "Europe/Moscow",
	"Krasnoyarsk":                "Asia/Krasnoyarsk",
	"Kryvyi Rih":                 "Europe/Kiev",
	"Kuala Lumpur":               "Asia/Kuala_Lumpur",
	"Kuching":                    "Asia/Kuching",
	"Kumamoto":                   "Asia/Tokyo",
	"Kumasi":                     "Africa/Accra",
	"Kunming":                    "Asia/Shanghai",
	"Kunshan":                    "Asia/Shanghai",
	"Kurashiki":                  "Asia/Tokyo",
	"Kurnool":                    "Asia/Kolkata",
	"Kyiv":                       "Europe/Kiev",
	"Kyoto":                      "Asia/Tokyo",
	"Köln":                       "Europe/Berlin",
	"La Paz":                     "America/La_Paz",
	"La Plata":                   "America/Argentina/Buenos_Aires",
	"Lagos":                      "Africa/Lagos",
	"Lahore":                     "Asia/Karachi",
	"Langfang":                   "Asia/Shanghai",
	"Lanzhou":                    "Asia/Shanghai",
	"Las Piñas":                  "Asia/Manila",
	"Las Vegas":                  "America/Los_Angeles",
	"Leeds":                      "Europe/London",
	"Leicester":                  "Europe/London",
	"Leipzig":                    "Europe/Berlin",
	"León de los Aldama":         "America/Mexico_City",
	"Liaoyang":                   "Asia/Shanghai",
	"Liaoyuan":                   "Asia/Shanghai",
	"Libreville":                 "Africa/Libreville",
	"Lijiang":                    "Asia/Shanghai",
	"Likasi":                     "Africa/Lubumbashi",
	"Lilongwe":                   "Africa/Blantyre",
	"Lima":                       "America/Lima",
	"Lipetsk":                    "Europe/Moscow",
	"Lisbon":                     "Europe/Lisbon",
	"Liverpool":                  "Europe/London",
	"Lomé":                       "Africa/Lome",
	"London":                     "Europe/London",
	"Londrina":                   "America/Sao_Paulo",
	"Long Beach":                 "America/Los_Angeles",
	"Los Angeles":                "America/Los_Angeles",
	"Luancheng":                  "Asia/Shanghai",
	"Luanda":                     "Africa/Luanda",
	"Lubumbashi":                 "Africa/Lubumbashi",
	"Lucknow":                    "Asia/Kolkata",
	"Ludhiāna":                   "Asia/Kolkata",
	"Luhansk":                    "Europe/Zaporozhye",
	"Luohe":                      "Asia/Shanghai",
	"Luoyang":                    "Asia/Shanghai",
	"Luqiao":                     "Asia/Shanghai",
	"Lusaka":                     "Africa/Lusaka",
	"Luxor":                      "Africa/Cairo",
	"Lviv":                       "Europe/Kiev",
	"Lyon":                       "Europe/Paris",
	"Macau":                      "Asia/Macau",
	"Maceió":                     "America/Maceio",
	"Madrid":                     "Europe/Madrid",
	"Madurai":                    "Asia/Kolkata",
	"Magnitogorsk":               "Asia/Yekaterinburg",
	"Maiduguri":                  "Africa/Lagos",
	"Makassar":                   "Asia/Makassar",
	"Makati City":                "Asia/Manila",
	"Makhachkala":                "Europe/Moscow",
	"Malang":                     "Asia/Jakarta",
	"Malatya":                    "Europe/Istanbul",
	"Malingao":                   "Asia/Manila",
	"Maltepe":                    "Europe/Istanbul",
	"Manado":                     "Asia/Makassar",
	"Managua":                    "America/Managua",
	"Manaus":                     "America/Manaus",
	"Mandalay":                   "Asia/Yangon",
	"Mangalore":                  "Asia/Kolkata",
	"Manhattan":                  "America/New_York",
	"Manila":                     "Asia/Manila",
	"Mansilingan":                "Asia/Manila",
	"Maputo":                     "Africa/Maputo",
	"Mar del Plata":              "America/Argentina/Buenos_Aires",
	"Maracaibo":                  "America/Caracas",
	"Maracay":                    "America/Caracas",
	"Mariupol":                   "Europe/Kiev",
	"Marrakesh":                  "Africa/Casablanca",
	"Marseille":                  "Europe/Paris",
	"Masan":                      "Asia/Seoul",
	"Mashhad":                    "Asia/Tehran",
	"Masina":                     "Africa/Kinshasa",
	"Matola":                     "Africa/Maputo",
	"Matsudo":                    "Asia/Tokyo",
	"Matsuyama":                  "Asia/Tokyo",
	"Mawlamyine":                 "Asia/Yangon",
	"Mbuji-Mayi":                 "Africa/Lubumbashi",
	"Mecca":                      "Asia/Riyadh",
	"Medan":                      "Asia/Jakarta",
	"Medellín":                   "America/Bogota",
	"Medina":                     "Asia/Riyadh",
	"Meerut":                     "Asia/Kolkata",
	"Meknès":                     "Africa/Casablanca",
	"Melbourne":                  "Australia/Melbourne",
	"Memphis":                    "America/Chicago",
	"Mendoza":                    "America/Argentina/Mendoza",
	"Mersin":                     "Europe/Istanbul",
	"Mesa":                       "America/Phoenix",
	"Mexicali":                   "America/Tijuana",
	"Mexico City":                "America/Mexico_City",
	"Miami":                      "America/New_York",
	"Milan":                      "Europe/Rome",
	"Milwaukee":                  "America/Chicago",
	"Minsk":                      "Europe/Minsk",
	"Mississauga":                "America/Toronto",
	"Mixco":                      "America/Guatemala",
	"Mogadishu":                  "Africa/Mogadishu",
	"Mombasa":                    "Africa/Nairobi",
	"Monrovia":                   "Africa/Monrovia",
	"Monterrey":                  "America/Monterrey",
	"Montevideo":                 "America/Montevideo",
	"Montréal":                   "America/Toronto",
	"Morelia":                    "America/Mexico_City",
	"Morādābād":                  "Asia/Kolkata",
	"Moscow":                     "Europe/Moscow",
	"Mosul":                      "Asia/Baghdad",
	"Mudanjiang":                 "Asia/Shanghai",
	"Multān":                     "Asia/Karachi",
	"Mumbai":                     "Asia/Kolkata",
	"Munich":                     "Europe/Berlin",
	"Muratpaşa":                  "Europe/Istanbul",
	"Murcia":                     "Europe/Madrid",
	"Muscat":                     "Asia/Muscat",
	"Muzaffarābād":               "Asia/Karachi",
	"Mwanza":                     "Africa/Dar_es_Salaam",
	"Mykolayiv":                  "Europe/Kiev",
	"Mysore":                     "Asia/Kolkata",
	"Málaga":                     "Europe/Madrid",
	"Mérida":                     "America/Merida",
	"Mālegaon":                   "Asia/Kolkata",
	"N'Djamena":                  "Africa/Ndjamena",
	"Naberezhnyye Chelny":        "Europe/Moscow",
	"Nagoya":                     "Asia/Tokyo",
	"Nagpur":                     "Asia/Kolkata",
	"Nairobi":                    "Africa/Nairobi",
	"Najaf":                      "Asia/Baghdad",
	"Namangan":                   "Asia/Tashkent",
	"Namp’o":                     "Asia/Pyongyang",
	"Nanchang":                   "Asia/Shanghai",
	"Nanchong":                   "Asia/Shanghai",
	"Nanded":                     "Asia/Kolkata",
	"Nangi":                      "Asia/Kolkata",
	"Nanjing":                    "Asia/Shanghai",
	"Nanning":                    "Asia/Shanghai",
	"Nantong":                    "Asia/Shanghai",
	"Naples":                     "Europe/Rome",
	"Nashik":                     "Asia/Kolkata",
	"Nashville":                  "America/Chicago",
	"Natal":                      "America/Fortaleza",
	"Naucalpan de Juárez":        "America/Mexico_City",
	"Navi Mumbai":                "Asia/Kolkata",
	"Nay Pyi Taw":                "Asia/Yangon",
	"Neijiang":                   "Asia/Shanghai",
	"New Kingston":               "America/Jamaica",
	"New South Memphis":          "America/Chicago",
	"New York City":              "America/New_York",
	"Niamey":                     "Africa/Niamey",
	"Niigata":                    "Asia/Tokyo",
	"Ningbo":                     "Asia/Shanghai",
	"Nishinomiya-hama":           "Asia/Tokyo",
	"Niterói":                    "America/Sao_Paulo",
	"Nizhniy Novgorod":           "Europe/Moscow",
	"North York":                 "America/Toronto",
	"Nottingham":                 "Europe/London",
	"Nouakchott":                 "Africa/Nouakchott",
	"Nova Iguaçu":                "America/Sao_Paulo",
	"Novokuznetsk":               "Asia/Novokuznetsk",
	"Novosibirsk":                "Asia/Novosibirsk",
	"Nowrangapur":                "Asia/Kolkata",
	"Nyala":                      "Africa/Khartoum",
	"Nürnberg":                   "Europe/Berlin",
	"Oakland":                    "America/Los_Angeles",
	"Odessa":                     "Europe/Kiev",
	"Okayama":                    "Asia/Tokyo",
	"Okene":                      "Africa/Lagos",
	"Oklahoma City":              "America/Chicago",
	"Omaha":                      "America/Chicago",
	"Omdurman":                   "Africa/Khartoum",
	"Omsk":                       "Asia/Omsk",
	"Onitsha":                    "Africa/Lagos",
	"Oran":                       "Africa/Algiers",
	"Ordos":                      "Asia/Shanghai",
	"Orenburg":                   "Asia/Yekaterinburg",
	"Orūmīyeh":                   "Asia/Tehran",
	"Osaka":                      "Asia/Tokyo",
	"Osasco":                     "America/Sao_Paulo",
	"Oslo":                       "Europe/Oslo",
	"Ottawa":                     "America/Toronto",
	"Ouagadougou":                "Africa/Ouagadougou",
	"Oyo":                        "Africa/Lagos",
	"Padang":                     "Asia/Jakarta",
	"Palembang":                  "Asia/Jakarta",
	"Palermo":                    "Europe/Rome",
	"Panshan":                    "Asia/Shanghai",
	"Paris":                      "Europe/Paris",
	"Pasay":                      "Asia/Manila",
	"Pasig City":                 "Asia/Manila",
	"Pasragad Branch":            "Asia/Tehran",
	"Patna":                      "Asia/Kolkata",
	"Pekanbaru":                  "Asia/Jakarta",
	"Penza":                      "Europe/Moscow",
	"Pereira":                    "America/Bogota",
	"Perm":                       "Asia/Yekaterinburg",
	"Perth":                      "Australia/Perth",
	"Peshawar":                   "Asia/Karachi",
	"Petaling Jaya":              "Asia/Kuala_Lumpur",
	"Philadelphia":               "America/New_York",
	"Phnom Penh":                 "Asia/Phnom_Penh",
	"Phoenix":                    "America/Phoenix",
	"Pietermaritzburg":           "Africa/Johannesburg",
	"Pikine":                     "Africa/Dakar",
	"Pimpri":                     "Asia/Kolkata",
	"Pingdingshan":               "Asia/Shanghai",
	"Pohang":                     "Asia/Seoul",
	"Pointe-Noire":               "Africa/Brazzaville",
	"Pontianak":                  "Asia/Pontianak",
	"Port Elizabeth":             "Africa/Johannesburg",
	"Port Harcourt":              "Africa/Lagos",
	"Port Said":                  "Africa/Cairo",
	"Port Sudan":                 "Africa/Khartoum",
	"Port-au-Prince":             "America/Port-au-Prince",
	"Portland":                   "America/Los_Angeles",
	"Porto Alegre":               "America/Sao_Paulo",
	"Poznań":                     "Europe/Warsaw",
	"Prague":                     "Europe/Prague",
	"Pretoria":                   "Africa/Johannesburg",
	"Pristina":                   "Europe/Belgrade",
	"Puebla":                     "America/Mexico_City",
	"Puente Alto":                "America/Santiago",
	"Pune":                       "Asia/Kolkata",
	"Puyang":                     "Asia/Shanghai",
	"Puyang Chengguanzhen":       "Asia/Shanghai",
	"Pyongyang":                  "Asia/Pyongyang",
	"Qingdao":                    "Asia/Shanghai",
	"Qinhuangdao":                "Asia/Shanghai",
	"Qionghai":                   "Asia/Shanghai",
	"Qiqihar":                    "Asia/Shanghai",
	"Qom":                        "Asia/Tehran",
	"Queens":                     "America/New_York",
	"Quetta":                     "Asia/Karachi",
	"Quezon City":                "Asia/Manila",
	"Quilmes":                    "America/Argentina/Buenos_Aires",
	"Quito":                      "America/Guayaquil",
	"Québec":                     "America/Toronto",
	"Rabat":                      "Africa/Casablanca",
	"Rahim Yar Khan":             "Asia/Karachi",
	"Raipur":                     "Asia/Kolkata",
	"Raleigh":                    "America/New_York",
	"Ranchi":                     "Asia/Kolkata",
	"Rasht":                      "Asia/Tehran",
	"Raurkela":                   "Asia/Kolkata",
	"Rawalpindi":                 "Asia/Karachi",
	"Ra’s Bayrūt":                "Asia/Beirut",
	"Recife":                     "America/Recife",
	"Reynosa":                    "America/Matamoros",
	"Ribeirão Preto":             "America/Sao_Paulo",
	"Riga":                       "Europe/Riga",
	"Rio de Janeiro":             "America/Sao_Paulo",
	"Riyadh":                     "Asia/Riyadh",
	"Rome":                       "Europe/Rome",
	"Rosario":                    "America/Argentina/Cordoba",
	"Rostov-na-Donu":             "Europe/Moscow",
	"Rotterdam":                  "Europe/Amsterdam",
	"Ryazan’":                    "Europe/Moscow",
	"Rājkot":                     "Asia/Kolkata",
	"Rājshāhi":                   "Asia/Dhaka",
	"Rāmgundam":                  "Asia/Kolkata",
	"Sacramento":                 "America/Los_Angeles",
	"Sahāranpur":                 "Asia/Kolkata",
	"Saint Petersburg":           "Europe/Moscow",
	"Saitama":                    "Asia/Tokyo",
	"Sakai":                      "Asia/Tokyo",
	"Sale":                       "Africa/Casablanca",
	"Salem":                      "Asia/Kolkata",
	"Salta":                      "America/Argentina/Salta",
	"Saltillo":                   "America/Monterrey",
	"Salvador":                   "America/Bahia",
	"Samara":                     "Europe/Samara",
	"San Antonio":                "America/Chicago",
	"San Diego":                  "America/Los_Angeles",
	"San Francisco":              "America/Los_Angeles",
	"San Jose":                   "America/Los_Angeles",
	"San Juan":                   "America/Puerto_Rico",
	"San Luis Potosí":            "America/Mexico_City",
	"San Miguel de Tucumán":      "America/Argentina/Tucuman",
	"San Nicolás de los Garza":   "America/Monterrey",
	"San Pedro Sula":             "America/Tegucigalpa",
	"San Salvador":               "America/El_Salvador",
	"Sanaa":                      "Asia/Aden",
	"Santa Cruz de la Sierra":    "America/La_Paz",
	"Santa Fe de la Vera Cruz":   "America/Argentina/Cordoba",
	"Santa Marta":                "America/Bogota",
	"Santa María Chimalhuacán":   "America/Mexico_City",
	"Santiago":                   "America/Santiago",
	"Santiago de Cuba":           "America/Havana",
	"Santiago de Querétaro":      "America/Mexico_City",
	"Santiago de los Caballeros": "America/Santo_Domingo",
	"Santo André":                "America/Sao_Paulo",
	"Santo Domingo":              "America/Santo_Domingo",
	"Santo Domingo Este":         "America/Santo_Domingo",
	"Santo Domingo Oeste":        "America/Santo_Domingo",
	"Santos":                     "America/Sao_Paulo",
	"Sapporo":                    "Asia/Tokyo",
	"Sarajevo":                   "Europe/Sarajevo",
	"Saratov":                    "Europe/Saratov",
	"Sargodha":                   "Asia/Karachi",
	"Scarborough":                "America/Toronto",
	"Seattle":                    "America/Los_Angeles",
	"Semarang":                   "Asia/Jakarta",
	"Sendai":                     "Asia/Tokyo",
	"Seongnam-si":                "Asia/Seoul",
	"Seoul":                      "Asia/Seoul",
	"Sevastopol":                 "Europe/Simferopol",
	"Sevilla":                    "Europe/Madrid",
	"Shah Alam":                  "Asia/Kuala_Lumpur",
	"Shanghai":                   "Asia/Shanghai",
	"Shangyu":                    "Asia/Shanghai",
	"Shantou":                    "Asia/Shanghai",
	"Shaoguan":                   "Asia/Shanghai",
	"Shaoxing":                   "Asia/Shanghai",
	"Sharjah":                    "Asia/Dubai",
	"Shashi":                     "Asia/Shanghai",
	"Sheffield":                  "Europe/London",
	"Shenyang":                   "Asia/Shanghai",
	"Shenzhen":                   "Asia/Shanghai",
	"Shihezi":                    "Asia/Urumqi",
	"Shijiazhuang":               "Asia/Shanghai",
	"Shiliguri":                  "Asia/Kolkata",
	"Shiraz":                     "Asia/Tehran",
	"Shivaji Nagar":              "Asia/Kolkata",
	"Shiyan":                     "Asia/Shanghai",
	"Shizuoka":                   "Asia/Tokyo",
	"Shuangyashan":               "Asia/Shanghai",
	"Shyamnagar":                 "Asia/Kolkata",
	"Shymkent":                   "Asia/Almaty",
	"Sialkot":                    "Asia/Karachi",
	"Singapore":                  "Asia/Singapore",
	"Siping":                     "Asia/Shanghai",
	"Situbondo":                  "Asia/Jakarta",
	"Skopje":                     "Europe/Skopje",
	"Sofia":                      "Europe/Sofia",
	"Sokoto":                     "Africa/Lagos",
	"Solāpur":                    "Asia/Kolkata",
	"Sorocaba":                   "America/Sao_Paulo",
	"South Boston":               "America/New_York",
	"South Tangerang":            "Asia/Jakarta",
	"Soweto":                     "Africa/Johannesburg",
	"Srinagar":                   "Asia/Kolkata",
	"Staten Island":              "America/New_York",
	"Stockholm":                  "Europe/Stockholm",
	"Stuttgart":                  "Europe/Berlin",
	"Subang Jaya":                "Asia/Kuala_Lumpur",
	"Suez":                       "Africa/Cairo",
	"Sukkur":                     "Asia/Karachi",
	"Sultangazi":                 "Europe/Istanbul",
	"Sulţānah":                   "Asia/Riyadh",
	"Sunch’ŏn":                   "Asia/Pyongyang",
	"Surabaya":                   "Asia/Jakarta",
	"Surakarta":                  "Asia/Jakarta",
	"Suwon":                      "Asia/Seoul",
	"Suzhou":                     "Asia/Shanghai",
	"Sydney":                     "Australia/Sydney",
	"São Bernardo do Campo":      "America/Sao_Paulo",
	"São José dos Campos":        "America/Sao_Paulo",
	"São João de Meriti":         "America/Sao_Paulo",
	"São Luís":                   "America/Fortaleza",
	"São Paulo":                  "America/Sao_Paulo",
	"Sāngli":                     "Asia/Kolkata",
	"Sūrat":                      "Asia/Kolkata",
	"Tabriz":                     "Asia/Tehran",
	"Tabuk":                      "Asia/Riyadh",
	"Taguig":                     "Asia/Manila",
	"Taichung":                   "Asia/Taipei",
	"Tainan":                     "Asia/Taipei",
	"Taipei":                     "Asia/Taipei",
	"Taiyuan":                    "Asia/Shanghai",
	"Taizhou":                    "Asia/Shanghai",
	"Tai’an":                     "Asia/Shanghai",
	"Takeo":                      "Asia/Phnom_Penh",
	"Tangerang":                  "Asia/Jakarta",
	"Tanggu":                     "Asia/Shanghai",
	"Tangier":                    "Africa/Casablanca",
	"Tangshan":                   "Asia/Shanghai",
	"Tashkent":                   "Asia/Tashkent",
	"Ta‘izz":                     "Asia/Aden",
	"Ta’if":                      "Asia/Riyadh",
	"Tbilisi":                    "Asia/Tbilisi",
	"Tegucigalpa":                "America/Tegucigalpa",
	"Tehran":                     "Asia/Tehran",
	"Tel Aviv":                   "Asia/Jerusalem",
	"Tembisa":                    "Africa/Johannesburg",
	"Teni":                       "Asia/Kolkata",
	"Teresina":                   "America/Fortaleza",
	"The Bronx":                  "America/New_York",
	"The Hague":                  "Europe/Amsterdam",
	"Thiruvananthapuram":         "Asia/Kolkata",
	"Thāne":                      "Asia/Kolkata",
	"Tianjin":                    "Asia/Shanghai",
	"Tianshui":                   "Asia/Shanghai",
	"Tijuana":                    "America/Tijuana",
	"Tiruchirappalli":            "Asia/Kolkata",
	"Tirunelveli":                "Asia/Kolkata",
	"Tlalnepantla":               "America/Mexico_City",
	"Tlalpan":                    "America/Mexico_City",
	"Tlaquepaque":                "America/Mexico_City",
	"Tokyo":                      "Asia/Tokyo",
	"Toluca":                     "America/Mexico_City",
	"Tol’yatti":                  "Europe/Samara",
	"Tomsk":                      "Asia/Tomsk",
	"Tonghua":                    "Asia/Shanghai",
	"Tongshan":                   "Asia/Shanghai",
	"Toronto":                    "America/Toronto",
	"Torreon":                    "America/Monterrey",
	"Touba":                      "Africa/Dakar",
	"Toulouse":                   "Europe/Paris",
	"Tripoli":                    "Africa/Tripoli",
	"Trujillo":                   "America/Lima",
	"Tucson":                     "America/Phoenix",
	"Tula":                       "Europe/Moscow",
	"Tunis":                      "Africa/Tunis",
	"Turin":                      "Europe/Rome",
	"Tuxtla":                     "America/Mexico_City",
	"Tyumen":                     "Asia/Yekaterinburg",
	"Tébessa":                    "Africa/Algiers",
	"Uberlândia":                 "America/Sao_Paulo",
	"Udaipur":                    "Asia/Kolkata",
	"Ufa":                        "Asia/Yekaterinburg",
	"Uijeongbu-si":               "Asia/Seoul",
	"Ujjain":                     "Asia/Kolkata",
	"Ulan Bator":                 "Asia/Ulaanbaatar",
	"Ulhasnagar":                 "Asia/Kolkata",
	"Ulsan":                      "Asia/Seoul",
	"Ulyanovsk":                  "Europe/Ulyanovsk",
	"Umraniye":                   "Europe/Istanbul",
	"Utsunomiya":                 "Asia/Tokyo",
	"Uyo":                        "Africa/Lagos",
	"Vadodara":                   "Asia/Kolkata",
	"Valencia":                   "Europe/Madrid",
	"Vancouver":                  "America/Vancouver",
	"Varanasi":                   "Asia/Kolkata",
	"Venustiano Carranza":        "America/Mexico_City",
	"Veracruz":                   "America/Mexico_City",
	"Vereeniging":                "Africa/Johannesburg",
	"Victoria de Durango":        "America/Monterrey",
	"Vienna":                     "Europe/Vienna",
	"Vijayawada":                 "Asia/Kolkata",
	"Vilnius":                    "Europe/Vilnius",
	"Virginia Beach":             "America/New_York",
	"Visakhapatnam":              "Asia/Kolkata",
	"Vladivostok":                "Asia/Vladivostok",
	"Volgograd":                  "Europe/Volgograd",
	"Voronezh":                   "Europe/Moscow",
	"Wandsbek":                   "Europe/Berlin",
	"Warangal":                   "Asia/Kolkata",
	"Warri":                      "Africa/Lagos",
	"Warsaw":                     "Europe/Warsaw",
	"Washington, D.C.":           "America/New_York",
	"Welkom":                     "Africa/Johannesburg",
	"Wenshan City":               "Asia/Shanghai",
	"Wenzhou":                    "Asia/Shanghai",
	"Winnipeg":                   "America/Winnipeg",
	"Wrocław":                    "Europe/Warsaw",
	"Wuhan":                      "Asia/Shanghai",
	"Wuhu":                       "Asia/Shanghai",
	"Wuwei":                      "Asia/Shanghai",
	"Wuxi":                       "Asia/Shanghai",
	"Xalapa de Enríquez":         "America/Mexico_City",
	"Xiamen":                     "Asia/Shanghai",
	"Xiangtan":                   "Asia/Shanghai",
	"Xiangyang":                  "Asia/Shanghai",
	"Xianyang":                   "Asia/Shanghai",
	"Xingtai":                    "Asia/Shanghai",
	"Xining":                     "Asia/Shanghai",
	"Xinxiang":                   "Asia/Shanghai",
	"Xinyang":                    "Asia/Shanghai",
	"Xi’an":                      "Asia/Shanghai",
	"Xuchang":                    "Asia/Shanghai",
	"Yancheng":                   "Asia/Shanghai",
	"Yangon":                     "Asia/Yangon",
	"Yangquan":                   "Asia/Shanghai",
	"Yangzhou":                   "Asia/Shanghai",
	"Yantai":                     "Asia/Shanghai",
	"Yaoundé":                    "Africa/Douala",
	"Yaroslavl":                  "Europe/Moscow",
	"Yazd":                       "Asia/Tehran",
	"Yekaterinburg":              "Asia/Yekaterinburg",
	"Yerevan":                    "Asia/Yerevan",
	"Yichang":                    "Asia/Shanghai",
	"Yinchuan":                   "Asia/Shanghai",
	"Yingkou":                    "Asia/Shanghai",
	"Yogyakarta":                 "Asia/Jakarta",
	"Yokohama":                   "Asia/Tokyo",
	"Yokosuka":                   "Asia/Tokyo",
	"Yono":                       "Asia/Tokyo",
	"Yueyang":                    "Asia/Shanghai",
	"Yunfu":                      "Asia/Shanghai",
	"Zagreb":                     "Europe/Zagreb",
	"Zahedan":                    "Asia/Tehran",
	"Zamboanga":                  "Asia/Manila",
	"Zapopan":                    "America/Mexico_City",
	"Zaporizhia":                 "Europe/Zaporozhye",
	"Zaragoza":                   "Europe/Madrid",
	"Zaria":                      "Africa/Lagos",
	"Zarqa":                      "Asia/Amman",
	"Zhangjiakou":                "Asia/Shanghai",
	"Zhangzhou":                  "Asia/Shanghai",
	"Zhanjiang":                  "Asia/Urumqi",
	"Zhengzhou":                  "Asia/Shanghai",
	"Zhenjiang":                  "Asia/Shanghai",
	"Zhongshan":                  "Asia/Urumqi",
	"Zhu Cheng City":             "Asia/Shanghai",
	"Zhuhai":                     "Asia/Shanghai",
	"Zhumadian":                  "Asia/Shanghai",
	"Zhuzhou":                    "Asia/Shanghai",
	"Zibo":                       "Asia/Shanghai",
	"Zigong":                     "Asia/Shanghai",
	"Zunyi":                      "Asia/Shanghai",
	"Álvaro Obregón":             "America/Mexico_City",
	"Çankaya":                    "Europe/Istanbul",
	"Ürümqi":                     "Asia/Urumqi",
	"Üsküdar":                    "Europe/Istanbul",
	"Āsansol":                    "Asia/Kolkata",
	"Āzādshahr":                  "Asia/Tehran",
	"İzmir":                      "Europe/Istanbul",
	"Łódź":                       "Europe/Warsaw",
	"Ōita":                       "Asia/Tokyo",
	"Şanlıurfa":                  "Europe/Istanbul",
	"Ḩamāh":                      "Asia/Damascus",
}
